using Il2Cpp;
using MelonLoader;
using UnityEngine;

namespace TweaksAndFixes.Modules
{
    internal class PredefinedDesignsData
    {
        public class PlayerTechData
        {
            public bool isDisabled;

            public int maxTechLevel;

            public int minTechLevel;

            public PlayerTechData(bool isDisabled, int maxTechLevel, int minTechLevel)
            {
                this.isDisabled = isDisabled;
                this.maxTechLevel = maxTechLevel;
                this.minTechLevel = minTechLevel;
            }
        }

        public class PredefFileData
        {
            [Serializer.Field]
            public string group;

            [Serializer.Field]
            public string filename;

            [Serializer.Field]
            public string player;

            [Serializer.Field]
            public int year_min;

            [Serializer.Field]
            public int year_max;

            public bool loaded;
        }

        public class PredefData
        {
            [Serializer.Field]
            public string name;

            [Serializer.Field]
            public float skipChance;

            public readonly Dictionary<string, List<int>> yearsPerPlayer = new Dictionary<string, List<int>>();

            public bool loadedData;

            public float _curSkipChance;
        }


        private static PredefinedDesignsData? _Instance = null;

        private const string _StockAssetName = "<stock predefined designs>";

        private const string _StockAssetFilenameProxy = "--";

        public static GameObject? _BatchGenUI = null;

        private bool _loaded;

        private bool _noFile = true;

        private bool _lastLoadCared;

        private readonly List<PredefData> _predefData = new List<PredefData>();

        private readonly List<PredefFileData> _predefFileData = new List<PredefFileData>();

        private Dictionary<string, PlayerTechData> _playerTechData = new Dictionary<string, PlayerTechData>();

        private int _lastValidData;

        private bool _needUseNewFindCode;

        private static bool PredefinedDesignFileProblem = false;

        private static bool hasBSGConfig = false;

        public static PredefinedDesignsData Instance
        {
            get
            {
                Ensure();
                return _Instance;
            }
        }

        public bool LastLoadWasRestrictive => _lastLoadCared;

        public bool NeedUseNewFindCode => _needUseNewFindCode;

        private static void Ensure()
        {
            if (_Instance == null)
            {
                _Instance = new PredefinedDesignsData();
            }
            if (!_Instance._loaded)
            {
                _Instance.LoadData();
            }
        }

        public static bool NeedLoadRestrictive()
        {
            return CampaignController.Instance.designsUsage == CampaignController.DesignsUsage.FullPredefined;
        }

        private void LoadData()
        {
            _loaded = false;
            _predefData.Clear();
            string dataText;
            string fileDataText;
            if (Config._PredefinedDesignsDataFile.Exists && Config._PredefinedDesignsFileDataFile.Exists)
            {
                _noFile = false;
                dataText = File.ReadAllText(Config._PredefinedDesignsDataFile.path);
                fileDataText = File.ReadAllText(Config._PredefinedDesignsFileDataFile.path);
            }
            else
            {
                Melon<TweaksAndFixes>.Logger.Msg("Missing `predefinedDesignsFiles.csv` and/or `predefinedDesignsData.csv`, using builtin predefs. See the TAF Wiki for more info on custom predefined designs.");
                _noFile = true;
                dataText = "@name,skipChance\nAutogenerated,0";
                fileDataText = "@group,filename,player,year_min,year_max\nAutogenerated,--,all,-1,-1";
            }
            _needUseNewFindCode = !_noFile || Config.DontClobberTechForPredefs;
            Melon<TweaksAndFixes>.Logger.Msg("Loading predefined design database");
            Serializer.CSV.Read<List<PredefData>, PredefData>(dataText, _predefData);
            Serializer.CSV.Read<List<PredefFileData>, PredefFileData>(fileDataText, _predefFileData);
            _loaded = true;
        }

        public bool LoadPredefSets(bool prewarm, bool update = false, bool loadAll = false)
        {
            if (PredefinedDesignFileProblem)
            {
                return false;
            }

            Patch_GameManager.CurrentSubGameState = Patch_GameManager.SubGameState.LoadingPredefinedDesigns;
            
            int num = 0;
            _lastValidData = 0;
            if (!update)
            {
                _lastLoadCared = false;
            }
            
            bool isCampaignStart = prewarm;
            bool hasNonStockData = false;

            if (!loadAll)
            {
                _playerTechData.Clear();
                foreach (var player in CampaignController.Instance.CampaignData.PlayersMajor)
                {
                    if (player.isDisabled || !player.isAi)
                    {
                        _playerTechData.Add(player.data.name, new PlayerTechData(isDisabled: true, -1, -1));
                        continue;
                    }
                    Dictionary<string, int> latestTechsOfType = new Dictionary<string, int>();
                    int maxTechYear = int.MinValue;
                    int minTechYear = int.MaxValue;
                    foreach (var tech in player.technologies)
                    {
                        if (tech.progress != 100f && (!tech.IsEndTechResearched || tech.Index <= 0))
                        {
                            continue;
                        }

                        int techYear = GameManager.GetTechYear(tech.data, sort: true);
                        if (techYear != -1)
                        {
                            if (!latestTechsOfType.ContainsKey(tech.data.type))
                            {
                                latestTechsOfType.Add(tech.data.type, techYear);
                            }

                            else if (techYear > latestTechsOfType[tech.data.type])
                            {
                                latestTechsOfType[tech.data.type] = techYear;
                            }
                        }
                    }

                    Melon<TweaksAndFixes>.Logger.Msg("For " + player.data.name);
                    foreach (KeyValuePair<string, int> latestTechOfType in latestTechsOfType)
                    {
                        if (latestTechOfType.Value > maxTechYear)
                        {
                            maxTechYear = latestTechOfType.Value;
                        }

                        if (latestTechOfType.Value < minTechYear)
                        {
                            minTechYear = latestTechOfType.Value;
                        }
                    }

                    Melon<TweaksAndFixes>.Logger.Msg($"  tech range = {minTechYear} - {maxTechYear}");
                    _playerTechData.Add(player.data.name, new PlayerTechData(isDisabled: false, maxTechYear, minTechYear));
                }
            }

            for (int dataIndex = _predefData.Count - 1; dataIndex >= 0; dataIndex--)
            {
                PredefData predefData = _predefData[dataIndex];
                
                if (prewarm || loadAll)
                {
                    predefData.yearsPerPlayer.Clear();
                    predefData.loadedData = false;
                }

                if (isCampaignStart)
                {
                    Melon<TweaksAndFixes>.Logger.Msg($"Replaced _currentDesigns because {prewarm} == {isCampaignStart}!");
                    _lastValidData = dataIndex;
                    predefData._curSkipChance = 0f;
                    CampaignController.Instance._currentDesigns = CampaignDesigns.FromStore(new CampaignDesigns().ToStore());
                }

                for (int i = 0; i < _predefFileData.Count; i++)
                {
                    PredefFileData predefFileData = _predefFileData[i];
                    if (prewarm)
                    {
                        predefFileData.loaded = false;
                    }

                    if ((!loadAll && predefFileData.loaded)
                        || (!loadAll && predefFileData.player != "all" && _playerTechData[predefFileData.player].isDisabled))
                    {
                        continue;
                    }

                    if (!loadAll && predefFileData.year_min != -1 && predefFileData.year_max != -1)
                    {
                        PlayerTechData playerTechData = _playerTechData[predefFileData.player];
                        int num5 = predefFileData.year_max - predefFileData.year_min + 1;
                        _ = playerTechData.maxTechLevel;
                        _ = playerTechData.maxTechLevel % num5;
                        if ((predefFileData.year_min < playerTechData.minTechLevel && predefFileData.year_max < playerTechData.minTechLevel) || predefFileData.year_max >= playerTechData.maxTechLevel)
                        {
                            continue;
                        }
                    }

                    string text;
                    string text2;
                    if (predefFileData.filename == "--")
                    {
                        text = null;
                        text2 = "<stock predefined designs>";
                    }

                    else
                    {
                        text2 = predefFileData.filename;
                        text = Path.Combine(Config._BasePath, "PredefinedDesigns", predefFileData.filename);
                        if (!File.Exists(text))
                        {
                            if (!_noFile)
                            {
                                Melon<TweaksAndFixes>.Logger.Error($"Failed to find predefined designs file {text2} referenced in {Config._PredefinedDesignsDataFile}");
                                continue;
                            }
                            text = null;
                            text2 = "<stock predefined designs>";
                        }
                    }

                    if (!LoadPredefs(text, out CampaignDesigns.Store store, out int dCount))
                    {
                        Melon<TweaksAndFixes>.Logger.Error("Tried to load predefined designs file " + text2 + " but failed to load it correctly.");
                        continue;
                    }

                    if (text != null)
                    {
                        hasNonStockData = true;
                    }
                    
                    Melon<TweaksAndFixes>.Logger.Msg($"  Loaded {dCount} designs from {text2}");
                    if (isCampaignStart)
                    {
                        foreach (var spy in store.shipsPerYear)
                        {
                            foreach (var spp in spy.Value.shipsPerPlayer)
                            {
                                PlayerData playerData = G.GameData.players[spp.Key];
                                CampaignControllerM.CachePlayerTechs(CampaignController.Instance.CampaignData.PlayersByData[playerData]);
                                predefData.yearsPerPlayer.ValueOrNew(spp.Key).Add(spy.Key);
                                foreach (var spt in spp.Value.shipsPerType)
                                {
                                    foreach (var design in spt.Value)
                                    {
                                        CampaignController.Instance._currentDesigns.AddShip(design);
                                    }
                                }
                            }
                        }

                        if (_needUseNewFindCode)
                        {
                            foreach (var spy in store.shipsPerYear)
                            {
                                foreach (var spp in spy.Value.shipsPerPlayer)
                                {
                                    predefData.yearsPerPlayer.ValueOrNew(spp.Key).Add(spy.Key);
                                }
                            }
                        }
                    }
                    else
                    {
                        foreach (var spy in store.shipsPerYear)
                        {
                            foreach (var spp in spy.Value.shipsPerPlayer)
                            {
                                predefData.yearsPerPlayer.ValueOrNew(spp.Key).Add(spy.Key);
                                string playerName = $"{dataIndex}_{spp.Key}";
                                foreach (var spt in spp.Value.shipsPerType)
                                {
                                    foreach (var design in spt.Value)
                                    {
                                        string playerName2 = design.playerName;
                                        design.playerName = playerName;
                                        CampaignController.Instance._currentDesigns.AddShip(design);
                                        design.playerName = playerName2;
                                    }
                                }
                            }
                        }
                    }

                    num += dCount;
                    predefData.loadedData = true;
                    predefFileData.loaded = true;
                }

                if (isCampaignStart)
                {
                    isCampaignStart = false;
                }

                foreach (KeyValuePair<string, List<int>> item2 in predefData.yearsPerPlayer)
                {
                    item2.Value.Sort();
                }
            }

            if (hasNonStockData)
            {
                Melon<TweaksAndFixes>.Logger.Msg($"Loaded {num} predefined designs. Loaded years {CampaignController.Instance._currentDesigns.shipsPerYear.Count}");
            }

            if (!update)
            {
                _lastLoadCared = prewarm;
            }

            Melon<TweaksAndFixes>.Logger.Msg($"_lastLoadCared = {_lastLoadCared}");
            Patch_GameManager.CurrentSubGameState = Patch_GameManager.SubGameState.Other;
            return true;
        }

        public static bool LoadPredefs(string? path, out CampaignDesigns.Store? store, out int dCount)
        {
            store = null;
            dCount = 0;
            return false;
        }

        public Ship.Store GetRandomShip(Player player, ShipType type, int desiredYear)
        {
            LoadPredefSets(prewarm: false, update: true);
            string name = player.data.name;
            if (desiredYear < Config.StartingYear)
            {
                _ = Config.StartingYear;
            }

            PlayerTechData playerTechData = _playerTechData[player.data.name];
            for (int i = 0; i < _predefData.Count; i++)
            {
                PredefData predefData = _predefData[i];
                if (!predefData.loadedData
                    || predefData.skipChance > UnityEngine.Random.value
                    || !predefData.yearsPerPlayer.ContainsKey(name))
                {
                    continue;
                }

                string dataName = (_lastValidData == i) ? name : $"{i}_{name}";
                List<Ship.Store> designList = new List<Ship.Store>(10);
                int designsChecked = 0;
                int yearStart = 0;
                int yearEnd = 0;
                int year = playerTechData.maxTechLevel;

                while (year > playerTechData.minTechLevel - 10 && designList.Count < 10)
                {
                    if (!CampaignController.Instance._currentDesigns.shipsPerYear.TryGetValue(year, out var shipsPerYear)
                        || !shipsPerYear.shipsPerPlayer.TryGetValue(dataName, out var shipsPerPlayer))
                        continue;

                    if (yearStart == 0)
                        yearStart = year;

                    yearEnd = year;

                    if (!shipsPerPlayer.shipsPerType.TryGetValue(type.name, out var shipsPerType))
                        continue;

                    foreach (var design in shipsPerType)
                    {
                        designsChecked++;
                                
                        if (CampaignControllerM.TechMatchRatio(design) >= 0f)
                            continue;

                        designList.Add(design);

                        if (designList.Count >= 10)
                            break;
                    }

                    year--;
                }

                Melon<TweaksAndFixes>.Logger.Msg($"Found {designList.Count}/10 options out of {designsChecked} designs checked in year {desiredYear} with tech range {yearStart} to {yearEnd}.");
                
                if (designList.Count != 0)
                {
                    return designList[0];
                }
            }
            return null;
        }
    }
}
